run:
  skip-dirs:
    - tmp
  go: '1.19'
linters:
  enable-all: true
  disable:
    - contextcheck
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - goerr113
    - golint
    - gomnd
    - gosec
    - ifshort
    - interfacer
    - lll
    - maligned
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
issues:
  fix: true