apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-secret-validation-webhook.fullname" . }}
  labels:
    {{- include "docker-secret-validation-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "docker-secret-validation-webhook.selectorLabels" . | nindent 4 }}
